# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeoAccess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoAccess

  target 'GeoAccess-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GeoAccessTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GeoAccess-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GeoAccess-tvOS

  target 'GeoAccess-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
